version: "3"
services:
  develop:
    build: .
    ports:
      - "3600:3600"
    container_name: gfw-guira-loss-api-develop
    environment:
      PORT: 3600
      NODE_PATH: app/src
      NODE_ENV: dev
      CARTODB_USER: wri-test
      CT_URL: http://mymachine:9000
      API_VERSION: v1
      CT_REGISTER_MODE: auto
    command: develop
    volumes:
      - ./app:/opt/gfw-guira-loss-api/app
