prod:
  image: vizzuality/gfw-guira-loss-api:1.0.0${STAGING}
  ports:
    - "3600"
  env_file:
    - prod.env
  command: start
  log_driver: "gelf"
  dns: ${DNS_SERVER}
  restart: always
  log_opt:
    gelf-address: ${GELF_ADDRESS}
