version: "3"
services:
  develop:
    build: .
    ports:
      - "3601:3601"
    container_name: gfw-guira-loss-api-develop
    environment:
      PORT: 3601
      NODE_PATH: app/src
      NODE_ENV: dev
      CARTODB_USER: wri-test
      GATEWAY_URL: http://mymachine:9000
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      LOCAL_URL: http://mymachine:3601
      FASTLY_ENABLED: "false"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
    command: develop
    volumes:
      - ./app:/opt/gfw-guira-loss-api/app
