apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: gfw
  name: gfw-guira
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: gfw-guira
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
